name: Behave + Selenium + Allure

on:
  push:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      BROWSER: chrome
      HEADLESS: "true"
      ALLURE_RESULTS_DIR: reports/allure-results
      ALLURE_REPORT_DIR: reports/allure-report

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run Behave (Allure results)
        run: |
          mkdir -p "$ALLURE_RESULTS_DIR"
          python -m behave -f allure_behave.formatter:AllureFormatter -o "$ALLURE_RESULTS_DIR" -f pretty

      - name: Generate Allure HTML report
        if: always()
        uses: simple-elf/allure-report-action@v1.13
        with:
          allure_results: ${{ env.ALLURE_RESULTS_DIR }}
          allure_report:  ${{ env.ALLURE_REPORT_DIR }}

      - name: "Debug: list report content"
        if: always()
        run: |
          echo "PWD=$(pwd)"
          ls -la "${ALLURE_RESULTS_DIR}" || true
          ls -la "${ALLURE_REPORT_DIR}"  || true

      - name: Upload Allure HTML report (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ${{ env.ALLURE_REPORT_DIR }}

      - name: Upload Pages artifact
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.ALLURE_REPORT_DIR }}

  deploy:
    if: ${{ github.event_name == 'push' }}
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
